version: '3'
services:
  db:
    image: mysql:8.0
    env_file: .env
    # TODO: delete to use caching_sha2_password
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  api:
    build:
      context: backend/
      dockerfile: Dockerfile
      args:
        - WITHOUT_ENV=production
    command: ./bin/rails server -b 0.0.0.0
    env_file: .env
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/src
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    links:
      - db

volumes:
  mysql-data:
    driver: local
  bundle:
    driver: local
