on:
  push:
    branches:
      - master
    paths-ignore:
      - 'backend/'
      - '**/*.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - 'backend/'
      - '**/*.md'
      - 'LICENSE'

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  FRONTEND_IMAGE_TAG: mapin-frontend-dev:0.0.3
  FRONTEND_IMAGE_CACHE_TAG: mapin-frontend-dev-cache
  IMAGE_CACHE_DIR: /tmp/cache/docker-image
  IMAGE_CACHE_KEY: cache-image

jobs:
  image-cache-or-build:
    strategy:
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out code
      id: checkout
      uses: actions/checkout@v2
    
    - name: Generate dotenv
      id: generate-dotenv
      run: cp .env.sample .env

    - name: Cache docker image
      id: cache-docker-image
      uses: actions/cache@v1
      with:
        path: ${{ env.IMAGE_CACHE_DIR }}
        key: ${{ runner.os }}-${{ env.IMAGE_CACHE_KEY }}-${{ hashFiles('frontend/package-lock.json') }}-${{ hashFiles('frontend/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.IMAGE_CACHE_KEY }}-
    - name: Docker load
      id: docker-load
      if: steps.cache-docker-image.outputs.cache-hit == 'true'
      run: docker image load -i ${IMAGE_CACHE_DIR}/image.tar

    - name: Docker build
      id: docker-build
      run: docker-compose build --build-arg BUILDKIT_INLINE_CACHE=1 --build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g) front

    - name: Docker tag and save
      id: docker-tag-save
      if: steps.cache-docker-image.outputs.cache-hit != 'true'
      run: mkdir -p ${IMAGE_CACHE_DIR}
        && docker image tag ${FRONTEND_IMAGE_TAG} ${FRONTEND_IMAGE_CACHETAG}
        && docker image save -o ${IMAGE_CACHE_DIR}/image.tar ${FRONTEND_IMAGE_CACHETAG}

  lint-dockerfile:
    strategy:
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out code
      id: checkout
      uses: actions/checkout@v2

    - name: hadolint
      id: hadolint
      run: docker run --rm -i hadolint/hadolint < frontend/Dockerfile

  test-app:
    needs: image-cache-or-build
    strategy:
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    env:
      NODE_MODULES_CACHE_DIR: /tmp/cache/node_modules
      NODE_MODULES_CACHE_KEY: cache-node_modules

    steps:
    - name: Check out code
      id: checkout
      uses: actions/checkout@v2

    - name: Generate dotenv
      id: generate-dotenv
      run: cp .env.sample .env

    - name: Cache docker image
      id: cache-docker-image
      uses: actions/cache@v1
      with:
        path: ${{ env.IMAGE_CACHE_DIR }}
        key: ${{ runner.os }}-${{ env.IMAGE_CACHE_KEY }}-${{ hashFiles('frontend/package-lock.json') }}-${{ hashFiles('frontend/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.IMAGE_CACHE_KEY }}-
    - name: Docker load
      id: docker-load
      if: steps.cache-docker-image.outputs.cache-hit == 'true'
      run: docker image load -i ${IMAGE_CACHE_DIR}/image.tar

    - name: Docker compose build
      id: docker-build
      run: docker-compose build --build-arg BUILDKIT_INLINE_CACHE=1 --build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g) front

    - name: Wait middleware services
      id: wait-middleware
      run: docker-compose up -d

    - name: Confirm docker-compose logs
      id: confirm-docker-compose-logs
      run: docker-compose logs
    
    - name: Cache node_modules
      id: cache-node_modules
      uses: actions/cache@v1
      with:
        path: ${{ env.NODE_MODULES_CACHE_DIR }}
        key: ${{ runner.os }}-${{ env.NODE_MODULES_CACHE_KEY }}-${{ hashFiles('frontend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.NODE_MODULES_CACHE_KEY }}-

    - name: Setup and Run test
      id: setup-and-run-test
      run: docker-compose run --rm frontend bash -c "npm test"


  scan-image-by-trivy:
    needs: image-cache-or-build
    strategy:
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    env:
      TRIVY_CACHE_DIR: /tmp/cache/trivy

    steps:
    - name: Check out code
      id: checkout
      uses: actions/checkout@v2

    - name: Cache docker image
      id: cache-docker-image
      uses: actions/cache@v1
      with:
        path: ${{ env.IMAGE_CACHE_DIR }}
        key: ${{ runner.os }}-${{ env.IMAGE_CACHE_KEY }}-${{ hashFiles('frontend/package-lock.json') }}-${{ hashFiles('frontend/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.IMAGE_CACHE_KEY }}-
    - name: Docker load
      id: docker-load
      if: steps.cache-docker-image.outputs.cache-hit == 'true'
      run: docker image load -i ${IMAGE_CACHE_DIR}/image.tar

    - name: Scan image
      id: scan-image
      run: docker container run
        --rm
        -v /var/run/docker.sock:/var/run/docker.sock
        -v ${TRIVY_CACHE_DIR}:/root/.cache/
        aquasec/trivy
        ${FRONTEND_IMAGE_CACHETAG}

